"""Plan models — execution plans generated by the planner.

The planner decomposes a business goal into an ordered list of PlanSteps.
Each step tracks its status through the execution lifecycle.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from agent.core.types import StepStatus


class PlanStep(BaseModel):
    """A single step in an execution plan."""

    step_index: int
    description: str = Field(description="Human-readable description of what to do")
    expected_outcome: str = Field(
        default="",
        description="What we expect to see after this step succeeds",
    )
    status: StepStatus = StepStatus.PENDING
    error: str | None = None
    started_at: datetime | None = None
    completed_at: datetime | None = None

    def mark_in_progress(self) -> None:
        """Mark step as currently executing."""
        self.status = StepStatus.IN_PROGRESS
        self.started_at = datetime.utcnow()

    def mark_success(self) -> None:
        """Mark step as successfully completed."""
        self.status = StepStatus.SUCCESS
        self.completed_at = datetime.utcnow()

    def mark_failed(self, error: str) -> None:
        """Mark step as failed with error details."""
        self.status = StepStatus.FAILED
        self.error = error
        self.completed_at = datetime.utcnow()

    def mark_skipped(self, reason: str = "") -> None:
        """Mark step as skipped."""
        self.status = StepStatus.SKIPPED
        self.error = reason
        self.completed_at = datetime.utcnow()


class ExecutionPlan(BaseModel):
    """An ordered execution plan for achieving a business goal.

    Generated by the planner and refined as execution progresses.
    Steps can be added, reordered, or skipped based on observations.
    """

    goal: str = Field(description="The business goal this plan achieves")
    steps: list[PlanStep] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    is_complete: bool = False

    @property
    def current_step_index(self) -> int | None:
        """Index of the first pending or in-progress step."""
        for step in self.steps:
            if step.status in (StepStatus.PENDING, StepStatus.IN_PROGRESS):
                return step.step_index
        return None

    @property
    def current_step(self) -> PlanStep | None:
        """The current step being executed or next pending step."""
        idx = self.current_step_index
        if idx is not None:
            return self.steps[idx]
        return None

    @property
    def completed_steps(self) -> list[PlanStep]:
        """All steps that have been completed (success or failed)."""
        return [
            s
            for s in self.steps
            if s.status in (StepStatus.SUCCESS, StepStatus.FAILED, StepStatus.SKIPPED)
        ]

    @property
    def progress_pct(self) -> float:
        """Completion percentage."""
        if not self.steps:
            return 0.0
        return len(self.completed_steps) / len(self.steps) * 100

    def add_step(self, description: str, expected_outcome: str = "") -> PlanStep:
        """Add a new step to the end of the plan."""
        step = PlanStep(
            step_index=len(self.steps),
            description=description,
            expected_outcome=expected_outcome,
        )
        self.steps.append(step)
        return step

    def to_summary(self) -> str:
        """Produce a compact text summary of the plan for LLM context."""
        lines = [f"Plan for: {self.goal}", f"Progress: {self.progress_pct:.0f}%", ""]
        for step in self.steps:
            status_icon = {
                StepStatus.PENDING: "⬜",
                StepStatus.IN_PROGRESS: "🔄",
                StepStatus.SUCCESS: "✅",
                StepStatus.FAILED: "❌",
                StepStatus.SKIPPED: "⏭️",
            }.get(step.status, "❓")
            lines.append(f"  {status_icon} Step {step.step_index}: {step.description}")
            if step.error:
                lines.append(f"      Error: {step.error}")
        return "\n".join(lines)
