#!/usr/bin/env python3
"""Quick-start bootstrap: configure everything from minimal inputs.

Usage:
    python scripts/quickstart.py --instance-url https://devXXXXX.service-now.com \
        --sn-username <username> [--llm-provider google] [--subproduction]

Passwords and provider keys are prompted with hidden input when they are not
already present in the environment. Test mutations stay disabled by default.

This script:
1. Generates a strong JWT secret
2. Creates .env.local with all required settings
3. Creates the database if it doesn't exist
4. Initializes the local schema without creating a predictable API admin user

No Docker required — runs on local native machine.
"""
from __future__ import annotations

import argparse
import getpass
import os
import secrets
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def generate_env_local(
    instance_url: str,
    sn_username: str,
    sn_password: str,
    llm_api_key: str,
    embedding_api_key: str = "",
    moondream_key: str = "",
    gemini_key: str = "",
    llm_provider: str = "google",
    is_subproduction: bool = False,
    allow_mutations: bool = False,
) -> str:
    """Generate the .env.local file content from minimal inputs."""
    jwt_secret = secrets.token_urlsafe(48)
    # Extract hostname from instance URL for allowlist
    from urllib.parse import urlparse
    parsed = urlparse(instance_url)
    hostname = parsed.hostname or instance_url.replace("https://", "").replace("http://", "").rstrip("/")

    provider_config = {
        "google": (
            "https://generativelanguage.googleapis.com/v1beta/openai/",
            "gemini-3.8-flash",
            "GEMINI_API_KEY",
        ),
        "nvidia": (
            "https://integrate.api.nvidia.com/v1",
            "nvidia/nemotron-3-ultra-550b-a55b",
            "OPENAI_API_KEY",
        ),
        "openai": ("", "gpt-4o", "OPENAI_API_KEY"),
    }
    base_url, model, api_key_name = provider_config[llm_provider]
    is_subproduction = bool(is_subproduction)
    allow_mutations = bool(allow_mutations and is_subproduction)

    env = f"""# ============================================================
# Auto-generated by scripts/quickstart.py
# DO NOT COMMIT THIS FILE — it contains real credentials
# ============================================================

# --- ServiceNow Instance ---
SERVICENOW_INSTANCE_URL={instance_url.rstrip("/")}
SERVICENOW_USERNAME={sn_username}
SERVICENOW_PASSWORD={sn_password}
SERVICENOW_IS_SUBPRODUCTION={str(is_subproduction).lower()}
SERVICENOW_ALLOW_MUTATIONS={str(allow_mutations).lower()}
SERVICENOW_ALLOWED_INSTANCES={hostname}
# Do not declare these credentials as a UAT persona until the actual role is verified.
SERVICENOW_REQUIRE_PERSONA_FOR_BENCHMARK=true
SERVICENOW_ORACLE_PERSONA_CONSTRAINED=true

# --- LLM provider ---
LLM_PROVIDER={llm_provider}
LLM_BASE_URL={base_url}
LLM_MODEL={model}
LLM_EMBEDDING_MODEL=nvidia/nemotron-3-embed-1b
LLM_EMBEDDING_BASE_URL=https://integrate.api.nvidia.com/v1
LLM_EMBEDDING_DIMENSIONS=2048
{api_key_name}={llm_api_key}
LLM_EMBEDDING_API_KEY={embedding_api_key or llm_api_key}

# --- Perception (Moondream + Gemini) ---
MOONDREAM_API_KEY={moondream_key}
GEMINI_API_KEY={gemini_key}

# --- JWT Auth ---
JWT_SECRET_KEY={jwt_secret}
JWT_ALGORITHM=HS256

# --- Database (local PostgreSQL) ---
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/servicenow_qa

# --- Redis (local) ---
REDIS_URL=redis://127.0.0.1:6379/0
SESSION_STORE_TYPE=redis
CELERY_BROKER_URL=redis://127.0.0.1:6379/0
CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/1

# --- Browser (local, headed for inspection) ---
BROWSER_HEADLESS=false
BROWSER_KEEP_BROWSER_OPEN=false
BROWSER_SHOW_MOUSE_CURSOR=true

# --- Environment ---
UAT_RUNTIME_MODE=local
ENVIRONMENT=development
LOG_LEVEL=INFO
"""
    return env


def main() -> None:
    parser = argparse.ArgumentParser(description="Quick-start: configure everything from minimal inputs")
    parser.add_argument("--instance-url", required=True, help="ServiceNow instance URL")
    parser.add_argument("--sn-username", required=True, help="ServiceNow username")
    parser.add_argument("--llm-provider", choices=("google", "nvidia", "openai"), default="google")
    parser.add_argument("--subproduction", action="store_true", help="Explicitly confirm this is a non-production instance")
    parser.add_argument("--allow-mutations", action="store_true", help="Explicitly allow test mutations; requires --subproduction")
    parser.add_argument("--overwrite-env", action="store_true", help="Replace an existing .env.local file")
    parser.add_argument("--skip-db", action="store_true", help="Skip database creation/init")
    args = parser.parse_args()

    env_path = REPO_ROOT / ".env.local"
    if env_path.exists() and not args.overwrite_env:
        parser.error(".env.local already exists; refusing to overwrite credentials (use --overwrite-env if intentional)")
    sn_password = getpass.getpass("ServiceNow password (input hidden): ")
    api_key_env = {"google": "GEMINI_API_KEY", "nvidia": "NVIDIA_API_KEY", "openai": "OPENAI_API_KEY"}[args.llm_provider]
    llm_api_key = os.environ.get(api_key_env, "") or getpass.getpass(f"{args.llm_provider} API key (input hidden): ")
    embedding_api_key = os.environ.get("LLM_EMBEDDING_API_KEY") or os.environ.get("OPENAI_API_KEY", "")
    if args.llm_provider == "google" and not embedding_api_key:
        embedding_api_key = getpass.getpass("NVIDIA embedding API key (input hidden): ")

    print("[*] Quick-start: configuring UAT_poc for local execution")
    print(f"    Instance: {args.instance_url}")
    print(f"    Username: {args.sn_username}")
    print(f"    LLM provider: {args.llm_provider}")

    # 1. Generate .env.local
    env_content = generate_env_local(
        instance_url=args.instance_url,
        sn_username=args.sn_username,
        sn_password=sn_password,
        llm_api_key=llm_api_key,
        embedding_api_key=embedding_api_key,
        moondream_key=os.environ.get("MOONDREAM_API_KEY", ""),
        gemini_key=os.environ.get("GEMINI_API_KEY", "") if args.llm_provider != "google" else llm_api_key,
        llm_provider=args.llm_provider,
        is_subproduction=args.subproduction,
        allow_mutations=args.allow_mutations,
    )
    env_path.write_text(env_content)
    print(f"[+] Written: {env_path}")

    if args.skip_db:
        print("[*] Skipping database setup (--skip-db)")
        print("\n[+] Quick-start complete! Now run:")
        print("    powershell -ExecutionPolicy Bypass -File scripts/start-local.ps1")
        return

    # 2. Create database
    print("\n[*] Creating database...")
    try:
        subprocess.run(["createdb", "servicenow_qa"], check=False, capture_output=True)
        subprocess.run(
            ["psql", "-d", "servicenow_qa", "-c", "CREATE EXTENSION IF NOT EXISTS vector;"],
            check=True, capture_output=True,
        )
        print("[+] Database created")
    except Exception as e:
        print(f"[!] Database creation skipped (may already exist): {e}")

    # 3. Initialize schema only; never create a predictable API admin account.
    print("\n[*] Initializing schema...")
    os.chdir(REPO_ROOT)
    try:
        subprocess.run(
            [sys.executable, "scripts/init_db.py"],
            check=True, capture_output=False,
            env={**os.environ, "UAT_RUNTIME_MODE": "local", "ENVIRONMENT": "development"},
        )
        print("[+] Schema initialized")
    except Exception as e:
        print(f"[!] Schema init failed: {e}")
        print("    Make sure PostgreSQL is running and .env.local has correct DATABASE_URL")

    print("\n" + "=" * 60)
    print("[+] Quick-start complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("  1. Start services:")
    print("     python -m uvicorn agent.main:app --host 0.0.0.0 --port 8000")
    print("     celery -A agent.core.celery_app worker --loglevel=info --pool=solo")
    print("  2. Check readiness:")
    print("     curl http://localhost:8000/api/v1/ready")
    print("  3. Bootstrap an application API user with a unique secret, if needed.")
    print("  4. Configure a separately verified non-admin UAT persona before any scored benchmark.")


if __name__ == "__main__":
    main()
