#!/usr/bin/env python3
"""Quick-start bootstrap: configure everything from minimal inputs.

Usage:
    python scripts/quickstart.py \
        --instance-url https://devXXXXX.service-now.com \
        --sn-username <username> \
        --sn-password <password> \
        --nvidia-key nvapi-xxx \
        [--moondream-key eyJ...] \
        [--gemini-key AI...]

This script:
1. Generates a strong JWT secret
2. Creates .env.local with all required settings
3. Creates the database if it doesn't exist
4. Initializes the schema + bootstraps admin user
5. Verifies readiness

No Docker required — runs on local native machine.
"""
from __future__ import annotations

import argparse
import os
import secrets
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def generate_env_local(
    instance_url: str,
    sn_username: str,
    sn_password: str,
    nvidia_key: str,
    moondream_key: str = "",
    gemini_key: str = "",
) -> str:
    """Generate the .env.local file content from minimal inputs."""
    jwt_secret = secrets.token_urlsafe(48)
    # Extract hostname from instance URL for allowlist
    from urllib.parse import urlparse
    parsed = urlparse(instance_url)
    hostname = parsed.hostname or instance_url.replace("https://", "").replace("http://", "").rstrip("/")

    # Determine if this looks like a subproduction instance
    is_sub = "dev" in hostname.lower() or "test" in hostname.lower() or "demo" in hostname.lower() or "uat" in hostname.lower() or "staging" in hostname.lower()

    env = f"""# ============================================================
# Auto-generated by scripts/quickstart.py
# DO NOT COMMIT THIS FILE — it contains real credentials
# ============================================================

# --- ServiceNow Instance ---
SERVICENOW_INSTANCE_URL={instance_url.rstrip("/")}
SERVICENOW_USERNAME={sn_username}
SERVICENOW_PASSWORD={sn_password}
SERVICENOW_IS_SUBPRODUCTION={"true" if is_sub else "false"}
SERVICENOW_ALLOW_MUTATIONS=true
SERVICENOW_ALLOWED_INSTANCES={hostname}

# --- Persona Configuration ---
# The provided credentials ARE the persona (non-admin)
SERVICENOW_PERSONAS={{"{sn_username}":{{"username":"{sn_username}","password":"{sn_password}","role":"itil"}}}}
SERVICENOW_ACTIVE_PERSONA={sn_username}
SERVICENOW_REQUIRE_PERSONA_FOR_BENCHMARK=true
SERVICENOW_ORACLE_PERSONA_CONSTRAINED=true

# --- LLM (NVIDIA NIM) ---
LLM_PROVIDER=nvidia
LLM_BASE_URL=https://integrate.api.nvidia.com/v1
LLM_MODEL=nvidia/nemotron-3-ultra-550b-a55b
LLM_EMBEDDING_MODEL=nvidia/nemotron-3-embed-1b-8k
LLM_EMBEDDING_BASE_URL=https://integrate.api.nvidia.com/v1
LLM_EMBEDDING_DIMENSIONS=2048
OPENAI_API_KEY={nvidia_key}

# --- Perception (Moondream + Gemini) ---
MOONDREAM_API_KEY={moondream_key}
GEMINI_API_KEY={gemini_key}

# --- JWT Auth ---
JWT_SECRET_KEY={jwt_secret}
JWT_ALGORITHM=HS256

# --- Database (local PostgreSQL) ---
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/servicenow_qa

# --- Redis (local) ---
REDIS_URL=redis://127.0.0.1:6379/0
SESSION_STORE_TYPE=redis
CELERY_BROKER_URL=redis://127.0.0.1:6379/0
CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/1

# --- Browser (local, headed for inspection) ---
BROWSER_HEADLESS=false
BROWSER_KEEP_BROWSER_OPEN=false
BROWSER_SHOW_MOUSE_CURSOR=true

# --- Environment ---
UAT_RUNTIME_MODE=local
ENVIRONMENT=development
LOG_LEVEL=INFO
"""
    return env


def main() -> None:
    parser = argparse.ArgumentParser(description="Quick-start: configure everything from minimal inputs")
    parser.add_argument("--instance-url", required=True, help="ServiceNow instance URL")
    parser.add_argument("--sn-username", required=True, help="ServiceNow username")
    parser.add_argument("--sn-password", required=True, help="ServiceNow password")
    parser.add_argument("--nvidia-key", required=True, help="NVIDIA NIM API key")
    parser.add_argument("--moondream-key", default="", help="Moondream API key")
    parser.add_argument("--gemini-key", default="", help="Gemini API key")
    parser.add_argument("--skip-db", action="store_true", help="Skip database creation/init")
    args = parser.parse_args()

    print("[*] Quick-start: configuring UAT_poc for local execution")
    print(f"    Instance: {args.instance_url}")
    print(f"    Username: {args.sn_username}")
    print(f"    LLM: NVIDIA NIM")

    # 1. Generate .env.local
    env_content = generate_env_local(
        instance_url=args.instance_url,
        sn_username=args.sn_username,
        sn_password=args.sn_password,
        nvidia_key=args.nvidia_key,
        moondream_key=args.moondream_key,
        gemini_key=args.gemini_key,
    )
    env_path = REPO_ROOT / ".env.local"
    env_path.write_text(env_content)
    print(f"[+] Written: {env_path}")

    if args.skip_db:
        print("[*] Skipping database setup (--skip-db)")
        print("\n[+] Quick-start complete! Now run:")
        print("    python scripts/start-local.ps1  # or start manually")
        return

    # 2. Create database
    print("\n[*] Creating database...")
    try:
        subprocess.run(["createdb", "servicenow_qa"], check=False, capture_output=True)
        subprocess.run(
            ["psql", "-d", "servicenow_qa", "-c", "CREATE EXTENSION IF NOT EXISTS vector;"],
            check=True, capture_output=True,
        )
        print("[+] Database created")
    except Exception as e:
        print(f"[!] Database creation skipped (may already exist): {e}")

    # 3. Initialize schema + bootstrap admin
    print("\n[*] Initializing schema...")
    os.chdir(REPO_ROOT)
    try:
        subprocess.run(
            [sys.executable, "scripts/init_db.py"],
            check=True, capture_output=False,
            env={**os.environ, "UAT_RUNTIME_MODE": "local", "ENVIRONMENT": "development"},
        )
        print("[+] Schema initialized")
    except Exception as e:
        print(f"[!] Schema init failed: {e}")
        print("    Make sure PostgreSQL is running and .env.local has correct DATABASE_URL")

    # 4. Bootstrap admin user
    print("\n[*] Bootstrapping admin user...")
    try:
        subprocess.run(
            [sys.executable, "scripts/bootstrap_admin.py",
             "--username", "qa-admin", "--password", "QuickStart123!"],
            check=True, capture_output=False,
        )
        print("[+] Admin user created (username: qa-admin, password: QuickStart123!)")
    except Exception as e:
        print(f"[!] Admin bootstrap failed: {e}")

    print("\n" + "=" * 60)
    print("[+] Quick-start complete!")
    print("=" * 60)
    print("\nNext steps:")
    print("  1. Start services:")
    print("     python -m uvicorn agent.main:app --host 0.0.0.0 --port 8000")
    print("     celery -A agent.core.celery_app worker --loglevel=info --pool=solo")
    print("  2. Check readiness:")
    print("     curl http://localhost:8000/api/v1/ready")
    print("  3. Get auth token:")
    print("     curl -X POST http://localhost:8000/api/v1/token -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=password&username=qa-admin&password=QuickStart123!'")
    print("  4. Seed golden environment:")
    print("     python scripts/seed_golden_environment.py --instance-url <url> --username <sn_username> --password <sn_password>")
    print("  5. Run benchmark:")
    print("     python scripts/run_incident_benchmark.py --instance-url <url> --persona <sn_username> --runs 3 --admin-token <JWT>")


if __name__ == "__main__":
    main()
